### ISSUE TITLE
Can not sprite png file which decoded from *dl.sc file

### ISSUE THREAD

**Issue by AceBee007** [Galaxy1036/Old-Sc-Dumper#2]
Now, I'm trying to sprite some texture in Clash Royale.
I used an old dumpersc.py from `https://github.com/Galaxy1036/Old-Sc-Dumper` to get png file from *dl.sc files.(For example: chr_magic_archer_dl.sc -> chr_magic_archer_dl.png)
And I decoded it with quickbms and I got some file without extension name. (chr_magic_archer_dl)
And when I execute the command python3 ./sc_decode.py -s chr_somechr, I just got a folder with white png files.

I want to know how to fix it.

**Comment by Galaxy1036** [comment]
https://github.com/Galaxy1036/Old-Sc-Dumper/issues/1 answered there
